#forum config
forum:
  jwt:
    expiration: 86400000
    secret: c3ByaW5nIGJvb3QgZm9ydW0tYXBpIDIwMjAtMDktMTMgMTE6NTE6MjA=
# data source 
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #create database forum character set utf8mb4 collate utf8mb4_0900_ai_ci
    url: jdbc:mysql://localhost:3306/forum?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
# jpa
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        
        